version: "3.8"
services:

  catalog-mongodb:
    image: mongo:4.2
    container_name: catalog-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo catalog-mongodb:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s